fix evaluator loading

diff --git a/db/data/evaluators.yml b/db/data/evaluators.yml
--- a/db/data/evaluators.yml
+++ b/db/data/evaluators.yml
@@ -7,7 +7,7 @@ screbleu:
     #SBATCH -p plgrid
     #SBATCH -N 1
     #SBATCH --ntasks-per-node=1
-    #SBATCH --mem=512M
+    #SBATCH --mem=10GB
     #SBATCH --job-name=sacrebleu
     #SBATCH --time=00:02:00
 
@@ -41,51 +41,47 @@ screbleu:
   tasks:
     - MT
     - ST
-  input_modality:
-    - text
-  output_modality:
-    - text
+  # from: text
+  to: text
 
-blueurt:
-  name: BLEURT
-  script: |
-    #!/bin/bash -l
+# blueurt:
+#   name: BLEURT
+#   script: |
+#     #!/bin/bash -l
 
-    #SBATCH -A plgmeetween2025-gpu-a100
-    #SBATCH -p plgrid-gpu-a100
-    #SBATCH -N 1
-    #SBATCH --ntasks-per-node=1
-    #SBATCH --gres=gpu:1
-    #SBATCH --mem=50G
-    #SBATCH --job-name=bleurt
-    #SBATCH --time=00:10:00
+#     #SBATCH -A plgmeetween2025-gpu-a100
+#     #SBATCH -p plgrid-gpu-a100
+#     #SBATCH -N 1
+#     #SBATCH --ntasks-per-node=1
+#     #SBATCH --gres=gpu:1
+#     #SBATCH --mem=50G
+#     #SBATCH --job-name=bleurt
+#     #SBATCH --time=00:10:00
 
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
 
-    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-bleurt__athena.sh
+#     calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-bleurt__athena.sh
 
-    output=$(bash $calculator_script -n $SOURCE_LANGUAGE $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
-    if [ "$?" -eq 0 ]; then
-      echo "Submitting output: $output"
-      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
-    else
-      echo "Error while calculating scores"
-      exit 1
-    fi
-  host: athena.cyfronet.pl
-  metrics:
-    - name: bleurt
-      order: asc
-      worst_score: 1
-      best_score: 0
-  tasks:
-    - MT
-    - ST
-  input_modality:
-    - text
-  output_modality:
-    - text
+#     output=$(bash $calculator_script -n $SOURCE_LANGUAGE $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+#     if [ "$?" -eq 0 ]; then
+#       echo "Submitting output: $output"
+#       curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
+#     else
+#       echo "Error while calculating scores"
+#       exit 1
+#     fi
+#   host: athena.cyfronet.pl
+#   metrics:
+#     - name: bleurt
+#       order: asc
+#       worst_score: 1
+#       best_score: 0
+#   tasks:
+#     - MT
+#     - ST
+#   from: text
+#   to: text
 
 wer:
   name: WER
@@ -120,18 +116,48 @@ wer:
       worst_score: 1
       best_score: 0
   tasks:
-    #  - MT # not sure if it should be here - check Gdrive table
-    #  - ST
     - ASR
-    - TTS
+  # from:
+  # - audio
+  to: text
+
+wer_tsv:
+  name: WER TSV
+  script: |
+    #!/bin/bash -l
+
+    #SBATCH -A plgmeetween2025-cpu
+    #SBATCH -p plgrid
+    #SBATCH -N 1
+    #SBATCH --ntasks-per-node=1
+    #SBATCH --mem=10GB
+    #SBATCH --job-name=wer
+    #SBATCH --time=00:02:00
+
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
+
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-tsv-wer__ares.sh
+
+    output=$(bash $calculator_script $SOURCE_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+    if [ "$?" -eq 0 ]; then
+      echo "Submitting output: $output"
+      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
+    else
+      echo "Error while calculating scores"
+      exit 1
+    fi
+  host: ares.cyfronet.pl
+  metrics:
+    - name: wer
+      order: asc
+      worst_score: 1
+      best_score: 0
+  tasks:
     - LIPREAD
-  input_modality:
-    - audio
-    - video
-    - text
-  output_modality:
-    - text
-    - audio
+  # from:
+  # - video
+  to: text
 
 rogue:
   name: ROGUE
@@ -144,7 +170,7 @@ rogue:
     #SBATCH --ntasks-per-node=1
     #SBATCH --mem=512M
     #SBATCH --job-name=rourge
-    #SBATCH --time=00:02:00
+    #SBATCH --time=72:00:00
 
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
@@ -176,11 +202,10 @@ rogue:
   tasks:
     - SUM
     - SSUM
-  input_modality:
-    - text
-    - audio
-  output_modality:
-    - text
+  # from:
+  # - text
+  # - audio
+  to: text
 
 accuracy:
   name: Accuracy
@@ -217,10 +242,8 @@ accuracy:
       best_score: 1
   tasks:
     - SQA
-  input_modality:
-    - audio
-  output_modality:
-    - text
+  # from: audio
+  to: text
 
 exact-match:
   name: Exact Match
@@ -257,10 +280,8 @@ exact-match:
       best_score: 1
   tasks:
     - SQA
-  input_modality:
-    - audio
-  output_modality:
-    - text
+  # from: audio
+  to: text
 
 f1-score:
   name: F1 Score
@@ -297,101 +318,97 @@ f1-score:
       best_score: 1
   tasks:
     - SQA
-  input_modality:
-    - audio
-  output_modality:
-    - text
+  # from: audio
+  to: text
 
-# NEW need to be tested!!!
-comet:
-  name: Comet
-  script: |
-    #!/bin/bash -l
+# # NEW need to be tested!!!
+# comet:
+#   name: Comet
+#   script: |
+#     #!/bin/bash -l
 
-    #SBATCH -A plgmeetween2025-gpu-a100
-    #SBATCH -p plgrid-gpu-a100
-    #SBATCH -N 1
-    #SBATCH --ntasks-per-node=1
-    #SBATCH --mem=50G
-    #SBATCH --job-name=comet
-    #SBATCH --time=00:10:00
+#     #SBATCH -A plgmeetween2025-gpu-a100
+#     #SBATCH -p plgrid-gpu-a100
+#     #SBATCH -N 1
+#     #SBATCH --ntasks-per-node=1
+#     #SBATCH --mem=50G
+#     #SBATCH --job-name=comet
+#     #SBATCH --time=00:10:00
 
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/input $INPUT_URL
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/input $INPUT_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
 
-    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-comet__athena.sh
+#     calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-comet__athena.sh
 
-    output=$(bash $calculator_script $SCRATCHDIR/input $SOURCE_LANGUAGE $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+#     output=$(bash $calculator_script $SCRATCHDIR/input $SOURCE_LANGUAGE $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
 
-    if [ "$?" -eq 0 ]; then
-      echo "Submitting output: $output"
-      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
-    else
-      echo "Error while calculating scores"
-      exit 1
-    fi
-  host: athena.cyfronet.pl
-  metrics:
-    - name: comet
-      order: desc
-      worst_score: 0
-      best_score: 1
-  tasks:
-    - MT
-    - ST
-  input_modality:
-    - text
-    - audio
-  output_modality:
-    - text
+#     if [ "$?" -eq 0 ]; then
+#       echo "Submitting output: $output"
+#       curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
+#     else
+#       echo "Error while calculating scores"
+#       exit 1
+#     fi
+#   host: athena.cyfronet.pl
+#   metrics:
+#     - name: comet
+#       order: desc
+#       worst_score: 0
+#       best_score: 1
+#   tasks:
+#     - MT
+#     - ST
+#   from:
+#     - text
+#     - audio
+#   to: text
 
 # run-characTER__ares.sh
-characTER:
-  name: Charac TER
-  script: |
-    #!/bin/bash -l
+# characTER:
+#   name: Charac TER
+#   script: |
+#     #!/bin/bash -l
 
-    #SBATCH -A plgmeetween2025-cpu
-    #SBATCH -p plgrid
-    #SBATCH -N 1
-    #SBATCH --ntasks-per-node=1
-    #SBATCH --mem=512M
-    #SBATCH --job-name=characTER
-    #SBATCH --time=00:10:00
+#     #SBATCH -A plgmeetween2025-cpu
+#     #SBATCH -p plgrid
+#     #SBATCH -N 1
+#     #SBATCH --ntasks-per-node=1
+#     #SBATCH --mem=512M
+#     #SBATCH --job-name=characTER
+#     #SBATCH --time=00:10:00
 
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
-    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
+#     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
 
-    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-characTER__ares.sh
+#     calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-characTER__ares.sh
 
-    output=$(bash $calculator_script $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+#     output=$(bash $calculator_script $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
 
-    if [ "$?" -eq 0 ]; then
-      echo "Submitting output: $output"
-      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
-    else
-      echo "Error while calculating scores"
-      exit 1
-    fi
-  host: ares.cyfronet.pl
-  metrics:
-    - name: characTER
-      order: asc
-      worst_score: 1
-      best_score: 0
-  tasks:
-    - ST
-    - MT
-  input_modality:
-    - text
-    - audio
-  output_modality:
-    - text
+#     if [ "$?" -eq 0 ]; then
+#       echo "Submitting output: $output"
+#       curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "$output"
+#     else
+#       echo "Error while calculating scores"
+#       exit 1
+#     fi
+#   host: ares.cyfronet.pl
+#   metrics:
+#     - name: characTER
+#       order: asc
+#       worst_score: 1
+#       best_score: 0
+#   tasks:
+#     - ST
+#     - MT
+#   from:
+#   - text
+#   - audio
+#   to: text
 
 # run-SLU-metrics__ares.sh
-slu:
-  name: SLU Metrics
+ic:
+  name: Intent Accuracy
   script: |
     #!/bin/bash -l
 
@@ -401,12 +418,12 @@ slu:
     #SBATCH --ntasks-per-node=1
     #SBATCH --mem=1G
     #SBATCH --job-name=slu
-    #SBATCH --time=01:00:00
+    #SBATCH --time=72:00:00
 
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
 
-    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-f1__ares.sh
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-SLU-metrics__ares.sh
 
     output=$(bash $calculator_script $TARGET_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
 
@@ -419,24 +436,22 @@ slu:
     fi
   host: ares.cyfronet.pl
   metrics:
-    - name: slot_type_f1
-      order: desc
-      worst_score: 0
-      best_score: 1
-    - name: slot_value_cer
-      order: asc
-      worst_score: 1
-      best_score: 0
     - name: intent_accuracy
       order: desc
       worst_score: 0
       best_score: 1
+    # - name: slot_type_f1
+    #   order: desc
+    #   worst_score: 0
+    #   best_score: 1
+    # - name: slot_value_cer
+    #   order: asc
+    #   worst_score: 1
+    #   best_score: 0
   tasks:
     - SLU
-  input_modality:
-    - audio
-  output_modality:
-    - text
+  # from: audio
+  to: text
 
 # run-SQA-HF-metrics__ares.sh
 sqa-hf:
@@ -450,7 +465,7 @@ sqa-hf:
     #SBATCH --ntasks-per-node=1
     #SBATCH --mem=1G
     #SBATCH --job-name=sqaHF
-    #SBATCH --time=01:00:00
+    #SBATCH --time=72:00:00
 
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $GROUNDTRUTH_URL
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $HYPOTHESIS_URL
@@ -478,10 +493,8 @@ sqa-hf:
       best_score: 1
   tasks:
     - SQA
-  input_modality:
-    - audio
-  output_modality:
-    - text
+  # from: audio
+  to: text
 # run-TTS-wer-utmos__athena.sh
 # wer-utmos:
 #   name: WER Utmos
