Initial port or remaining evaluators

diff --git a/db/data/evaluators.yml b/db/data/evaluators.yml
--- a/db/data/evaluators.yml
+++ b/db/data/evaluators.yml
@@ -1,5 +1,5 @@
 screbleu:
-  name: Sacrebleu
+  name: SacreBLEU
   script: |
     #!/bin/bash -l
 
@@ -31,15 +31,10 @@ screbleu:
     - ter
   tasks:
     - MT
-    - SUM
     - ST
-    - SSUM
-    - SQA
-    - SLU
-    - LIPREAD
 
 blueurt:
-  name: bleurt
+  name: BLEURT
   script: |
     #!/bin/bash -l
 
@@ -49,7 +44,7 @@ blueurt:
     #SBATCH --ntasks-per-node=1
     #SBATCH --gres=gpu:1
     #SBATCH --mem=50G
-    #SBATCH --job-name=BLEURT
+    #SBATCH --job-name=bleurt
     #SBATCH --time=00:10:00
 
     curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $GROUNDTRUTH_URL
@@ -69,4 +64,176 @@ blueurt:
   metrics:
     - bleurt
   tasks:
+    - MT
     - ST
+
+wer:
+  name: WER
+  script: |
+    #!/bin/bash -l
+
+    #SBATCH -A plgmeetween2004-cpu
+    #SBATCH -p plgrid
+    #SBATCH -N 1
+    #SBATCH --ntasks-per-node=1
+    #SBATCH --mem=512M
+    #SBATCH --job-name=wer
+    #SBATCH --time=00:02:00
+
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $GROUNDTRUTH_URL
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $HYPOTHESIS_URL
+
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-wer__ares.sh
+
+    output=$(bash $calculator_script $SOURCE_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+    if [ "$?" -eq 0 ]; then
+      echo "Submitting output: $output"
+      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "{ \"scores\": $output}"
+    else
+      echo "Error while calculating scores"
+      exit 1
+    fi
+  host: ares.cyfronet.pl
+  metrics:
+    - wer
+  tasks:
+   - MT
+   - ST
+   - ASR
+   - LIPREAD
+
+
+rogue:
+  name: ROGUE
+  script: |
+    #!/bin/bash -l
+
+    #SBATCH -A plgmeetween2004-cpu
+    #SBATCH -p plgrid
+    #SBATCH -N 1
+    #SBATCH --ntasks-per-node=1
+    #SBATCH --mem=512M
+    #SBATCH --job-name=rourge
+    #SBATCH --time=00:02:00
+
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $GROUNDTRUTH_URL
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $HYPOTHESIS_URL
+
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-SUM-rouge__ares.sh
+
+    output=$(bash $calculator_script $SOURCE_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+    if [ "$?" -eq 0 ]; then
+      echo "Submitting output: $output"
+      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "{ \"scores\": $output}"
+    else
+      echo "Error while calculating scores"
+      exit 1
+    fi
+  host: ares.cyfronet.pl
+  metrics:
+    - rouge
+  tasks:
+    - SUM
+    - SSUM
+
+accuracy:
+  name: Accuracy
+  script: |
+    #!/bin/bash -l
+
+    #SBATCH -A plgmeetween2004-cpu
+    #SBATCH -p plgrid
+    #SBATCH -N 1
+    #SBATCH --ntasks-per-node=1
+    #SBATCH --mem=512M
+    #SBATCH --job-name=rourge
+    #SBATCH --time=00:02:00
+
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $GROUNDTRUTH_URL
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $HYPOTHESIS_URL
+
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-SQA-accuracy__ares.sh
+
+    output=$(bash $calculator_script $SOURCE_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+
+    if [ "$?" -eq 0 ]; then
+      echo "Submitting output: $output"
+      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "{ \"scores\": $output}"
+    else
+      echo "Error while calculating scores"
+      exit 1
+    fi
+  host: ares.cyfronet.pl
+  metrics:
+    - accuracy
+  tasks:
+    - SQA
+
+exact-match:
+  name: Exact Match
+  script: |
+    #!/bin/bash -l
+
+    #SBATCH -A plgmeetween2004-cpu
+    #SBATCH -p plgrid
+    #SBATCH -N 1
+    #SBATCH --ntasks-per-node=1
+    #SBATCH --mem=512M
+    #SBATCH --job-name=exact-match
+    #SBATCH --time
+
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $GROUNDTRUTH_URL
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $HYPOTHESIS_URL
+
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-exact-match__ares.sh
+
+    output=$(bash $calculator_script $SOURCE_LANGUAGE $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+
+    if [ "$?" -eq 0 ]; then
+      echo "Submitting output: $output"
+      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "{ \"scores\": $output}"
+    else
+      echo "Error while calculating scores"
+      exit 1
+    fi
+  host: ares.cyfronet.pl
+  metrics:
+    - exact-match
+  tasks:
+    - ASR
+    - LIPREAD
+
+
+
+f1-score:
+  name: F1 Score
+  script: |
+    #!/bin/bash -l
+
+    #SBATCH -A plgmeetween2004-cpu
+    #SBATCH -p plgrid
+    #SBATCH -N 1
+    #SBATCH --ntasks-per-node=1
+    #SBATCH --mem=512M
+    #SBATCH --job-name=f1-score
+    #SBATCH --time
+
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/hyp $GROUNDTRUTH_URL
+    curl --retry 5 --retry-max-time 600 --retry-connrefused -L -o $SCRATCHDIR/ref $HYPOTHESIS_URL
+
+    calculator_script=/net/pr2/projects/plgrid/plggmeetween/evaluation/run-f1__ares.sh
+
+    output=$(bash $calculator_script $SCRATCHDIR/hyp $SCRATCHDIR/ref)
+
+    if [ "$?" -eq 0 ]; then
+      echo "Submitting output: $output"
+      curl -X POST $RESULTS_URL -L --location-trusted -H "Content-Type:application/json" -H "Authorization:Token $TOKEN" -d "{ \"scores\": $output}"
+    else
+      echo "Error while calculating scores"
+      exit 1
+    fi
+  host: ares.cyfronet.pl
+  metrics:
+    - f1-score
+  tasks:
+    - SQA
